# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Demo1' do
pod 'SnapKit'
end

target 'Demo1Tests' do

end

target 'Demo1UITests' do

end

