# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Demo2' do
pod 'SnapKit'
end

target 'Demo2Tests' do

end

target 'Demo2UITests' do

end

